### ISSUE TITLE
Will it be possible to publish a version with the latest changes? 

### ISSUE THREAD

**Issue by wkirschbaum** [ericsalim/exemvi#7]
The current master branch has a few deprecation fixes. Will it be possible to publish this as a new version?

**Comment by ericsalim** [comment]
Hi, I did released it as version 0.2.2 two months ago. Could you verify?

**Comment by wkirschbaum** [comment]
@ericsalim sorry for the late reply, I missed the notification. Sorry, my mistake. It is there 🙈. Thanks for the release.
